name: Build and Push NGINX Docker Image  # Name of the GitHub Actions workflow

on:  # Define the trigger for the workflow
  push:  # Trigger the workflow on a git push
    branches:
      - main  # Only run this workflow when code is pushed to the 'main' branch

jobs:  # Define the jobs to run
  docker:  # Name of the job
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner provided by GitHub

    steps:  # The steps to execute in this job

      - uses: actions/checkout@v3  # Step 1: Checkout the repo so the workflow can access the code

      - name: Log in to Docker Hub  # Step 2: Authenticate to Docker Hub
        uses: docker/login-action@v3  # Use Docker's official login action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password/token stored in GitHub Secrets

      - name: Build and push NGINX image  # Step 3: Build and push Docker image
        uses: docker/build-push-action@v5  # Use Docker's build-push action to automate build and push
        with:
          context: .  # Build context: current directory (looks for Dockerfile here)
          push: true  # Push the built image to Docker Hub
          tags: kai554/test:nginxweb  # Tag for the Docker image (username/repo:tag)
